server:
  port: 8080
spring:
  application:
    name: redis-demo-v1
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=northwind;encrypt=false;trustServerCertificate=false
    username: sa
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        format-sql: 'true'
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'
  redis:
    host: localhost
    password:
    username:
    port: 6379